### ISSUE TITLE
Link-local address doesn't work

### ISSUE THREAD

**Issue by Citrullin** [eclipse/thingweb.node-wot#362] opened 2020-12-07 08:46 UTC
I got a local microcontroller with a wot td server on it.
When I call the link-local address with libcoap, I get the following response
```
./coap-client -m get coap://[fe80::9c7c:12ff:fe70:8f55%tapbr0]/.well-known/wot-thing-description
{"@context":["https://www.w3.org/2019/wot/td/v1",{"cov":"http://www.example.org/coap-binding#"},{"saref":"https://w3id.org/saref#"}],"securityDefinitions":{"basic_schema":{"scheme":"basic","descriptions":{"en":"Basic sec schema"},"description":"Basic sec schema","in":"query","name":"querykey"}},"security":["basic_schema"],"@type":["saref:LightSwitch"],"titles":{"en":"English title","de":"Deutscher Titel"},"title":"English title","descriptions":{"en":"English description","de":"Deutsche Beschreibung"},"description":"English description","properties":{"echo":{"observable":false,"forms":[{"op":["readproperty"],"href":"/echo","contentType":"text/plain","cov:methodName":"GET"}]}}
```
I am also able to see the coap block transfers in Wireshark.

I wrote a simple [node-wot application](https://github.com/Citrullin/wot-node-boilerplate). When I run this application with `yarn dev` it times out. 
```
yarn dev
yarn run v1.22.5
$ ts-node src/index.ts
[core/helpers] Helpers found scheme 'coap'
[core/servient] Servient creating client for scheme 'coap'
[binding-coap] CoapClientFactory creating client for 'coap'
[core/helpers] WoTImpl fetching TD from 'coap:[fe80::9c7c:12ff:fe70:8f55%tapbr0]/.well-known/wot-thing-description' with [CoapClient]
[binding-coap] CoapClient got Form 'contentType' application/td+json
[binding-coap] CoapClient sending GET to coap:[fe80::9c7c:12ff:fe70:8f55%tapbr0]/.well-known/wot-thing-description
Fetch error: Error: No reply in 247s
    at Timeout.<anonymous> (/home/citrullin/git/wot-nodejs/node_modules/coap/lib/retry_send.js:74:16)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  retransmitTimeout: 247
}
Done in 250.44s.
```
I also checked Wireshark in that case. But there isn't any traffic on this interface. So, my best guess is that the Helper isn't able to call a link-local address. Or maybe there is something wrong with my code. Since I haven't figured out the networking yet, I am not able to give it a routable ULA or global address.

**Comment by danielpeintner** [comment] 2022-09-16 12:35
Is this issue still valid?

**Comment by JKRhb** [comment] 2022-09-18 23:18
If I am not mistaken, this is actually an issue caused by Node itself (c.f., https://github.com/mcollina/node-coap/issues/334), as specifying the network interface (in this case `%tapbr0`) in the IPv6 address is not supported. Therefore, I think we could close this issue as fixing it is out of scope, unfortunately :/

**Comment by danielpeintner** [comment] 2022-09-19 07:08
Thanks @JKRhb for letting us know...

**Closed by danielpeintner** 2022-09-19 07:08 UTC
Labels: bug, binding-coap
