### ISSUE TITLE
[Browsified node-wot] Unknown theme foundation5

### ISSUE THREAD

**Issue by fatadel** [eclipse/thingweb.node-wot#274] opened 2020-07-06 07:42 UTC
In the [browsefied node-wot](http://plugfest.thingweb.io/webui) a form for filling in input data doesn't show up.
The error says:
```
jsoneditor.min.js:18 Uncaught Error: Unknown theme foundation5
    at new K (jsoneditor.min.js:18)
    at showSchemaEditor (index.js:111)
    at HTMLLIElement.item.onclick (index.js:56)
```
To reproduce the issue go to the site, consume the default `TestThing` and invoke any action except `void-void`.

**Comment by egekorkan** [comment] 2020-07-06 10:18
Interesting. I can confirm the bug but fetching of the foundation theme succeeds. The action `void-obj` does not represent the same error btw.

**Comment by egekorkan** [comment] 2020-07-06 10:19
Probably happening due to this line: https://github.com/eclipse/thingweb.node-wot/blob/5dc31997b7bcd8bee0248edc51548b14c874ea25/examples/browser/index.js#L114

Since the interactions that do not have an input omits this line somehow without showing an error, the bug regarding creating a JSON editor does not show itself

**Comment by danielpeintner** [comment] 2020-07-14 08:07
Not exactly sure "why" but the following line caused the issue

`JSONEditor.defaults.theme = 'foundation5';`

I fixed the issue in https://github.com/eclipse/thingweb.node-wot/pull/282 and already updated the [online version](http://plugfest.thingweb.io/webui) and everything seems to work fine *without* setting any default theme.

Please check and approve PR.

**Comment by egekorkan** [comment] 2020-07-14 08:09
Seems to work for me! :blush:

**Comment by danielpeintner** [comment] 2020-07-14 12:01
Merged https://github.com/eclipse/thingweb.node-wot/pull/282

**Closed by danielpeintner** 2020-07-14 12:01 UTC

**Comment by fatadel** [comment] 2020-07-16 14:19
Yeah, the problem is over. Thank you, @danielpeintner !
