### ISSUE TITLE
Counter client example hangs after execution

### ISSUE THREAD

**Issue by relu91** [eclipse/thingweb.node-wot#637] opened 2021-12-04 09:25 UTC
It seems that there is a resource leak in the counter example. My first impression is that CoAp client does not get properly cleaned up after the interaction with the remote thing. Maybe integrating https://github.com/mcollina/node-coap/pull/317 would help to solve the problem. 

### How to reproduce
Run `node packages/cli/dist/cli.js examples/scripts/counter.js` and in another shell `node packages/cli/dist/cli.js -c examples/scripts/counter-client.js`. The client application hangs without properly exiting.

**Comment by danielpeintner** [comment] 2021-12-06 11:55
@JKRhb do you know more?

**Comment by JKRhb** [comment] 2021-12-06 12:41
Hmm, when I try to execute `counter-client.js` I get the following error:

```
Invalid URL: /counter
Fetch error: Error: WoTImpl fetched invalid JSON from 'coap://localhost:5683/counter': Unexpected token I in JSON at position 0
```

Because of that I am not sure if the error arises from the CoAP library or from the Helper class. Does it terminate when fetching the TD with HTTP instead?

In any case, I think the close method will probably help with resolving issues like these :) I added it now to https://github.com/eclipse/thingweb.node-wot/pull/634. I am waiting for the merge of a type related PR over at node-coap. Once that one is merged the close method will hopefully land soon.

**Comment by JKRhb** [comment] 2021-12-06 17:43
> Thank you for testing @JKRhb, are you in sync with master? we've just merged a PR that should have solved the issue that you're mentioning.

Oh, yeah, you are right, I rebuilt the project and now I can reproduce the issue :) The issue seems to already occur when the TD is fetched – I commented out everything within the `try` block and the example still did not terminate. I guess #634 will probably fix this but it is a bit strange that the Agent does not close automatically as it should when there are no more messages in flight. When using HTTP instead for fetching, the problem does not occur I guess?

**Comment by danielpeintner** [comment] 2021-12-09 08:44
> When using HTTP instead for fetching, the problem does not occur I guess?

Correct.
To be sure I tried it locally and with _pure_ HTTP the client closes fine.

**Comment by JKRhb** [comment] 2022-01-01 23:19
I now discovered a potential fix/workaround for the `stop` method in the `coap-client`:

https://github.com/eclipse/thingweb.node-wot/blob/930798e6334f2b53566885615bfdeb4a2e48b8bc/packages/binding-coap/src/coap-client.ts#L189-L191

Setting the `agent` field to `null` after closing it actually causes the `counter-client` to properly terminate. 

```diff
    public async stop(): Promise<void> {
        this.agent.close();
+       this.agent = null;
    }
```

With this workaround the tests still seem to work (as a new `Agent` is created with each request, if I am not mistaken). I will still have a look into how this might be solved more elegantly in node-coap itself.

At least on my system, there seems to be another IPv6 related issue ("Destination Unreachable" according to Wireshark) causing the client to hang during these lines:

https://github.com/eclipse/thingweb.node-wot/blob/3a9c4ca6fe6eccefbf5ba0930df23fecd8daffbd/examples/scripts/counter-client.js#L37-L39

Does the execution of the client example hang there for you as well?

**Comment by danielpeintner** [comment] 2022-01-10 10:52
> Edit2: It is really odd that the problem only occurs when using CoAP for fetching a TD via the CLI.

In my case the client also hangs if I replace

`WoTHelpers.fetch("coap://localhost:5683/counter")`

with 

`WoTHelpers.fetch("http://localhost:8080/counter")`

Did you mean that?


> Does the execution of the client example hang there for you as well?

In my case the client does not hand. Having said that, I do not have any IPv6 addresses so I cannot tell what would happen if I would...

**Comment by relu91** [comment] 2022-03-16 09:31
I've opened the PR above which fixes the problem 😸 , let's wait for review -> merge -> and release

**Comment by JKRhb** [comment] 2022-03-17 12:11
@relu91 Can you check if the problem is still present after the merge of https://github.com/mcollina/node-coap/pull/329 and the new node-coap version? :)

**Comment by relu91** [comment] 2022-03-17 12:42
Yeah, I was testing it this morning. Good news first: it solves the "hang after fetch" problem. But the example still hangs 😢 . The problem is that node-wot does not usually `stop` clients after the execution of an affordance. Therefore, the coap client is never closed if you use it for an affordance. Now the problem is when we should close it?
1. We can't close just before returning from the affordance because the application needs to read the value from the socket (e.g using the `value` function)
2. We could in principle close it when the client has fully consumed the stream. I've tried it but it causes some problems with the HTTP client (probably because it is not clear to me if the same client riuse it)
3. Ideally it would be good to have a destroy method in the ConsumedThing interface that clean up all the resources (closing open clients)

Ideas? opinions?

**Comment by danielpeintner** [comment] 2022-03-17 13:26
> 3\. Ideally it would be good to have a destroy method in the ConsumedThing interface that clean up all the resources (closing open clients)

This would a discussion point for the Scripting API, right?

**Comment by relu91** [comment] 2022-03-17 13:27
> This would a discussion point for the Scripting API, right?

yeah, I think we can discuss it there.

**Comment by relu91** [comment] 2022-03-17 13:28
Another option is to consider to have some setting in the `coap` agent to automatically close the socket when a request/respose cycle is finished. @JKRhb what do you think?

**Comment by relu91** [comment] 2022-03-17 13:30
> "Why" did CoAP not hang in v0.7.x and does hang in v0.8.x. Does it relate again with the "stream" changes ?

That's a good question, TBH not sure why, one possible answer:
- we used to close the client in `consumed-thing` class since we didn't have to defer it because of streaming modes

**Closed** 2022-04-26 12:28 UTC
Labels: bug, binding-coap, cli, examples

**Comment by JKRhb** [comment] 2022-04-26 12:37
Just tried out the counter example once more and #744 finally fixed it :) Sorry for the all the trouble :/
