### ISSUE TITLE
Running example script fails with "Unexpected token export" error

### ISSUE THREAD

**Issue by danielpeintner** [eclipse/thingweb.node-wot#2] opened 2018-06-14 14:08 UTC
The tsc command fails to create a correct JS file.
When running for example "`node packages\cli\dist\cli.js  examples\scripts\counter.js`" I get

```
thingweb.node-wot\packages\cli\node_modules\wot-typescript-definitions\index.d.ts:1
(function (exports, require, module, __filename, __dirname) { export as namespace WoT;
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\Projects\WoT\thingweb\thingweb.node-wot\packages\c
li\dist\default-servient.js:17:36)
```

**Comment by mkovatsc** [comment] 2018-07-18 16:02
This was a problem caused by using enums from the wot-typescript-definitions.

The wot-typescript-definitions have  not been build, i.e., no .js has been created, so it crashes whenever they are used as dependency instead of a dev dependency for its types only.

The enums have been removed and the wot-typescript-definitions now use  discriminated unions.
Closing.

**Closed by mkovatsc** 2018-07-18 16:02 UTC

**Comment by danielpeintner** [comment] 2018-07-20 07:21
I wonder whether we should post an issue at [TypeScript](https://github.com/Microsoft/TypeScript).

To me it would seem more natural (and better) to use enums...

**Comment by mkovatsc** [comment] 2018-07-23 15:06
But it is not an issue with TypeScript. When you want to use Enums, you need to instantiate them in node-wot, and hence require a build step for the wot-typescript-definitions and make them full dependencies.

Discriminated unions are quite common to my understanding.
