### ISSUE TITLE
Helper fetch request hangs when fetching from CoAP URL.

### ISSUE THREAD

**Issue by FadySalama** [eclipse/thingweb.node-wot#802] opened 2022-07-12 10:02 UTC
My lab students encountered a bug when fetching a TD from a CoAP URL. The application hangs indefinitely. The CoAP servers are reachable using other CoAP clients and are able to fetch the TD normally. When the parsed TD is hard-coded in the application and consumed, the application works normally. I was able to reproduce that behavior.

Code:
```typescript
import { Servient, Helpers } from "@node-wot/core";
import { HttpClientFactory } from "@node-wot/binding-http";
import { CoapClientFactory } from "@node-wot/binding-coap";

const servient = new Servient();
servient.addClientFactory(new CoapClientFactory())

const WoTHelpers = new Helpers(servient)
// let TD: WoT.ThingDescription = {"@context":["https://www.w3.org/2019/wot/td/v1",{"@language":"en"}],"@type":"Thing","id":"de:tum:ei:esi:fp:coffee:2-6","title":"Virtual-Coffee-Machine_2_6","description":"A virtual coffee machine to learn the WoT TD standard","security":"nosec_sc","securityDefinitions":{"nosec_sc":{"scheme":"nosec"}},"properties":{"state":{"type":"string","readOnly":true,"enum":["Ready","Brewing","Error"],"forms":[{"href":"coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6/properties/state","contentType":"application/json","op":["readproperty"]}],"writeOnly":false,"observable":false},"waterStatus":{"type":"integer","readOnly":true,"unit":"%","maximum":100,"minimum":0,"forms":[{"href":"coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6/properties/waterStatus","contentType":"application/json","op":["readproperty"]}],"writeOnly":false,"observable":false},"coffeeStatus":{"type":"integer","readOnly":true,"unit":"%","maximum":100,"minimum":0,"forms":[{"href":"coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6/properties/coffeeStatus","contentType":"application/json","op":["readproperty"]}],"writeOnly":false,"observable":false},"binStatus":{"type":"integer","readOnly":true,"unit":"%","maximum":100,"minimum":0,"forms":[{"href":"coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6/properties/binStatus","contentType":"application/json","op":["readproperty"]}],"writeOnly":false,"observable":false}},"actions":{"brew":{"input":{"type":"string","enum":["latte-machiato","espresso","cappuccino"]},"forms":[{"href":"coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6/actions/brew","contentType":"application/json","op":"invokeaction"}],"idempotent":false,"safe":false},"abort":{"forms":[{"href":"coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6/actions/abort","contentType":"application/json","op":"invokeaction"}],"idempotent":false,"safe":false},"shutdown":{"forms":[{"href":"coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6/actions/shutdown","contentType":"application/json","op":"invokeaction"}],"idempotent":false,"safe":false}},"events":{"maintenance":{"data":{"type":"string"},"forms":[{"href":"coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6/events/maintenance","contentType":"application/json","op":"subscribeevent"}]},"error":{"data":{"type":"string"},"forms":[{"href":"coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6/events/error","contentType":"application/json","op":"subscribeevent"}]}}}

WoTHelpers.fetch('coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6').then(async (td) => {
    let TD = td as WoT.ThingDescription
    console.log(td)
    try {
        servient.start().then(async (WoT) => {
            // Then from here on you can consume the thing
            // i.e let thing = await WoT.consume(td) ...
            let prop = await (await (await WoT.consume(TD)).readProperty("waterStatus")).value()
            console.log(prop)
        });
    }
    catch (err) {
        console.error("Script error:", err);
    }
}).catch((err) => { console.error("Fetch error:", err); });
```

Console logs:
```
[core/helpers] Helpers found scheme 'coap'
[core/servient] Servient creating client for scheme 'coap'
[binding-coap] CoapClientFactory creating client for 'coap'
[core/helpers] WoTImpl fetching TD from 'coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6' with [CoapClient]
[binding-coap] CoapClient got Form 'contentType' application/td+json
[binding-coap] CoapClient sending GET to coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6
Fetch error: RetrySendError: No reply in 247 seconds.
    at Timeout.<anonymous> (C:\Phd\Programs\Testing\CoapClient\node_modules\coap\dist\lib\retry_send.js:56:25)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  retransmitTimeout: 247
}
```

**Comment by danielpeintner** [comment] 2022-07-12 13:02
I can confirm that 'coap://esiremotelab.esi.ei.tum.de:5683/Virtual-Coffee-Machine_2_6' can be fetched outside of node-wot.
Maybe @JKRhb knows more...

**Comment by JKRhb** [comment] 2022-07-18 02:12
I compared a request outside node-wot with the one from the fetch helper using Wireshark and the difference is that node-wot sets an Accept option with a value of `application/td+json` which is not handled by the server/Thing. node-wot seems to work as intended (sending Retransmissions of the request which receive no response), the server, however, does not.

**Comment by danielpeintner** [comment] 2022-07-20 12:08
@FadySalama did you have time to look into that issue? Can we close the issue?

**Comment by danielpeintner** [comment] 2022-07-27 08:04
Closing.

@FadySalama please reopen if you think it is a node-wot issue...

**Closed by danielpeintner** 2022-07-27 08:04 UTC
Labels: binding-coap

**Comment by FadySalama** [comment] 2022-07-27 14:04
> Closing.
> 
> @FadySalama please reopen if you think it is a node-wot issue...

Sure, thanks @danielpeintner
