### ISSUE TITLE
EINVAL error on global IPv6 addresses

### ISSUE THREAD

**Issue by Citrullin** [eclipse/thingweb.node-wot#363] opened 2020-12-08 05:06 UTC
I used the [node-wot-boilerplate](https://github.com/Citrullin/wot-node-boilerplate) project. Instead of using a link-local address as mentioned in #362, I used a global IPv6 address. For example `2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54`
When I execute `yarn dev`, I get the following error
```
yarn dev
yarn run v1.22.5
$ ts-node src/index.ts
[core/helpers] Helpers found scheme 'coap'
[core/servient] Servient creating client for scheme 'coap'
[binding-coap] CoapClientFactory creating client for 'coap'
[core/helpers] WoTImpl fetching TD from 'coap:[2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54]/.well-known/wot-thing-description' with [CoapClient]
[binding-coap] CoapClient got Form 'contentType' application/td+json
[binding-coap] CoapClient sending GET to coap:[2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54]/.well-known/wot-thing-description
Fetch error: Error: send EINVAL 2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54:5683
    at doSend (dgram.js:692:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:429:12)
    at afterDns (dgram.js:638:5)
    at processTicksAndRejections (internal/process/task_queues.js:81:21) {
  errno: -22,
  code: 'EINVAL',
  syscall: 'send',
  address: '2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54,
  port: 5683
}
```
I guess the error here is that the IP address is not properly escaped. The parameter should be `[2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54]:5683` and not `2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54:5683`

**Comment by danielpeintner** [comment] 2020-12-08 10:28
Note: We should check whether this is a CoAP only issue or it applies to HTTP too.

**Comment by Citrullin** [comment] 2020-12-11 23:45
@danielpeintner Is there some timeline on this?

**Comment by danielpeintner** [comment] 2020-12-12 00:19
I will try to take a look next week.

Any help / PR is appreciated.

**Comment by danielpeintner** [comment] 2020-12-14 15:31
I believe it has to do with the `url` module we are using to retrieve the hostname, see

https://github.com/eclipse/thingweb.node-wot/blob/6979cc94dcfaef9554cb90a6f695f8cd027e15a7/packages/binding-coap/src/coap-client.ts#L172-L182

I think it does not what one would expect, see https://github.com/nodejs/node-v0.x-archive/issues/9404 ...

I did implement a dirty workaround but I cannot test IPv6 properly. May I ask you to take a look at the following PR https://github.com/eclipse/thingweb.node-wot/pull/369

**Comment by Citrullin** [comment] 2020-12-17 04:13
> I believe it has to do with the `url` module we are using to retrieve the hostname, see
> 
> https://github.com/eclipse/thingweb.node-wot/blob/6979cc94dcfaef9554cb90a6f695f8cd027e15a7/packages/binding-coap/src/coap-client.ts#L172-L182
> 
> I think it does not what one would expect, see [nodejs/node-v0.x-archive#9404](https://github.com/nodejs/node-v0.x-archive/issues/9404) ...
> 
> I did implement a dirty workaround but I cannot test IPv6 properly. @Citrullin may I ask you to take a look at the following PR #369

I already tried to get a development environment running. I had some issues and it takes ages to compile. Do you have some chat where I can ask you questions for faster interactions?

**Comment by Citrullin** [comment] 2020-12-17 06:35
I identified the problem. The `coap` package uses `udp4`, even though it should use `udp6`. I am currently checking, if bumping the version will fix this. `node-coap-client` already fixed this issue. Migrating to it would make sense. Also in order to be consistent with the `coaps` implementation, which already uses it.

The option used to create the request in the `coap` package:
```
{
  agent: Agent {
    _opts: { type: 'udp4' },
    _sock: Socket {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      type: 'udp4',
      [Symbol(kCapture)]: false,
      [Symbol(async_id_symbol)]: 10,
      [Symbol(state symbol)]: [Object]
    },
    _msgIdToReq: {},
    _tkToReq: {},
    _lastToken: 2381707627,
    _lastMessageId: 43715,
    _closing: false,
    _msgInFlight: 0,
    _requests: 0
  },
  hostname: '[2a01:c10a:d6ca:c212:9c7c:1bff:fe90:8f54]',
  port: NaN,
  pathname: '/.well-known/wot-thing-description',
  query: null,
  observe: false,
  multicast: false,
  confirmable: true,
  method: 'GET'
}
```

**Comment by relu91** [comment] 2021-03-01 15:30
I'd like to re-open the issue. It is not completely fixed. The problem still arises when you construct the CoapClientFactory using a server instance. Sadly, the coap agent when created with a socket as an option it ignores completely the type passed as an option:
```ts
let requestUri = url.parse(uri);
// this.agentOptions.socket = { instance }
let agentOptions = this.agentOptions;
agentOptions.type = net.isIPv6(requestUri.hostname) ? "udp6" : "udp4";
    
this.agent = new coap.Agent(agentOptions);

//this.agent._opts.type = 'udp4'
```

I am not sure why the server socket is passed to the client configuration but still, the issue remains. @danielpeintner  could you reopen it? @Citrullin could you propose a fix?

**Comment by Citrullin** [comment] 2021-03-01 15:57
@relu91As I remember I had to force the type to udp6, if the IP is IPv6. So yes, it should ignore it. I don't understand the problem. What problem arises when you use a server instance? Do you have an example?

**Comment by relu91** [comment] 2021-03-01 16:03
I think trying is the best explainer. You should reproduce the issue changing your node-wot boilerplate project index.ts to the following:
```ts
  
import { Servient, Helpers } from "@node-wot/core";
import { CoapClientFactory } from "@node-wot/binding-coap";

// create Servient and add CoAP binding
const servient = new Servient();
servient.addClientFactory(new CoapClientFactory(new CoapServer())); // you have to import CoapServer

const wotHelper = new Helpers(servient);
Promise.all(
  [
    wotHelper.fetch("coap:[fe80::9c7c:12ff:fe70:8f55%tapbr0]/.well-known/wot-thing-description"),
    servient.start()
  ]
).then((values) => {
  const td = values[0];
  const WoT = values[1];
  console.log(td)

  return WoT.consume(td).then((thing) => {
    console.log(thing)
    // read a property "string" and print the value
    return thing.readProperty("string").then((s) => {
        console.log(s)
    })
  });
}).catch((err) => { console.error("Fetch error:", err) })
```

**Comment by danielpeintner** [comment] 2022-04-21 13:23
Has this issue been fixed / solved?

**Comment by relu91** [comment] 2022-04-30 14:18
Not sure I've to test it again, do we have some TD hosted with IPv6 online?

**Comment by egekorkan** [comment] 2022-04-30 19:52
maybe from @Citrullin ? he had some in the last(?) plugfest

**Comment by Citrullin** [comment] 2022-04-30 20:15
> maybe from @Citrullin ? he had some in the last(?) plugfest

I tried to fix this in the last plugfest, but I couldn't quite figure it out as I remember. Or my fix introduced some other issues. I don't think we have an IPv6 device online. But if you need one, I can set one up for you. I just prefer to not run them for very long on a global public IPv6, since we don't have any security on them. I can also set one up for the next plugfest. 

I changed my ISP in the meantime. I hope this still works the same way, otherwise I have to figure it out :D

**Comment by JKRhb** [comment] 2022-04-30 21:15
If I remember correctly, there were some issues in node-coap which should be fixed by now :) Maybe we could add another test case just to be sure, though?

**Comment by danielpeintner** [comment] 2023-01-16 14:06
I assume we can close this issue then, right?

**Comment by relu91** [comment] 2023-01-16 14:13
I'm not confident about closing this issue without a test or an example... @JKRhb can you use the code snippet above to bake a unit test? or is it too time-consuming?

**Comment by JKRhb** [comment] 2023-01-16 15:22
Sure, I can add a test to resolve the issue :) I think the root cause was fixed by https://github.com/coapjs/node-coap/pull/267 by the way, IIRC.

**Comment by JKRhb** [comment] 2023-01-17 11:22
See #910 for a potential fix :)

**Closed** 2023-01-18 07:40 UTC
Labels: bug, good first issue, binding-coap
